apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
data:
  config: |
    [default]
    region = us-east-1
  syncs3.sh: |
    export AWS_CONFIG_FILE="/root/.aws/config" #change it as per user
    export AWS_ACCESS_KEY_ID=AKIAUA3QHDVNB6BW6GVO
    export AWS_SECRET_ACCESS_KEY=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
    aws s3 sync /var/log/nginx s3://nginx-logs-dee-1